apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: apps
spec:
  defaultBackend:
    service:
      name: paperless-ngx
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - paperless
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: n8n
#   namespace: apps
# spec:
#   defaultBackend:
#     service:
#       name: paperless-ngx
#       port:
#         name: http
#   ingressClassName: tailscale
#   tls:
#     - hosts:
#         - paperless
